//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelMid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupReportTimeNew
    {
        public int id { get; set; }
        public string testOrder { get; set; }
        public string textGroup { get; set; }
        public Nullable<int> ReciveType { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> min { get; set; }
        public string Remark { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string restDay { get; set; }
        public string restWeek { get; set; }
        public string orderId { get; set; }
        public string Report_Place { get; set; }
        public string fixTime { get; set; }
        public int isEmergen { get; set; }
    }
}
