//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS_Config
    {
        public int Id { get; set; }
        public string Q_Priority_ElderlyAge { get; set; }
        public string Q_Priority_TestItem { get; set; }
        public string Q_Priority_ItemTube { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
