//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Config
    {
        public int ID { get; set; }
        public string SoftwareType { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string Indexes { get; set; }
        public string Explain { get; set; }
        public string Value { get; set; }
    }
}
