//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_LabelConfirm
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string UserName { get; set; }
        public string Barcode { get; set; }
        public string Request { get; set; }
        public string Result { get; set; }
        public Nullable<int> Res { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
