//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LR
    {
        public string BarCode { get; set; }
        public string Department { get; set; }
        public string Bed { get; set; }
        public string SampleName { get; set; }
        public int LableType { get; set; }
        public int PrintCount { get; set; }
        public string TubeColor { get; set; }
        public string TestGroup { get; set; }
        public string TestOrder { get; set; }
        public string EmergenteInfo { get; set; }
        public string BS01 { get; set; }
        public string BS02 { get; set; }
        public string BS03 { get; set; }
        public string BS04 { get; set; }
        public string BS05 { get; set; }
        public string BS06 { get; set; }
        public string BS07 { get; set; }
        public string BS08 { get; set; }
        public string BS09 { get; set; }
        public string BS10 { get; set; }
        public string PatientID { get; set; }
        public string PatientType { get; set; }
        public string PatientName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string AgeUnit { get; set; }
        public string PS01 { get; set; }
        public string PS02 { get; set; }
        public string PS03 { get; set; }
        public string PS04 { get; set; }
        public string PS05 { get; set; }
        public string PS06 { get; set; }
        public string PS07 { get; set; }
        public string PS08 { get; set; }
        public string PS09 { get; set; }
        public string PS10 { get; set; }
        public string LS01 { get; set; }
        public string LS02 { get; set; }
        public string LS03 { get; set; }
        public string LS04 { get; set; }
        public string LS05 { get; set; }
        public string LS06 { get; set; }
        public string LS07 { get; set; }
        public string LS08 { get; set; }
        public string LS09 { get; set; }
        public string LS10 { get; set; }
        public string UserID { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime PrintTime { get; set; }
        public int PickStatus { get; set; }
        public System.DateTime PickTime { get; set; }
        public bool CheckStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
