//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Data
    {
        public long ID { get; set; }
        public string PatientID { get; set; }
        public string PatientType { get; set; }
        public string PatientName { get; set; }
        public string PatientSex { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public string PatientAgeUnit { get; set; }
        public string BarCode { get; set; }
        public string Department { get; set; }
        public string BedNo { get; set; }
        public string SampleName { get; set; }
        public Nullable<int> LableType { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string TubeColor { get; set; }
        public string TubeGroup { get; set; }
        public string TubeItem { get; set; }
        public string EmergenteInfo { get; set; }
        public Nullable<System.DateTime> LabelPrintTime { get; set; }
        public Nullable<int> LabelPushState { get; set; }
        public Nullable<System.DateTime> LabelPushTime { get; set; }
        public Nullable<int> SortingState { get; set; }
        public Nullable<System.DateTime> SortingTime { get; set; }
        public Nullable<int> SortingPushState { get; set; }
        public Nullable<System.DateTime> SortingPushTime { get; set; }
        public string SortingNum { get; set; }
        public string SortingBar { get; set; }
        public string SortingPrintState { get; set; }
        public string PushOperator { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RepeatInsert { get; set; }
        public string DeviceID { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string PS01 { get; set; }
        public string PS02 { get; set; }
        public string PS03 { get; set; }
        public string PS04 { get; set; }
        public string PS05 { get; set; }
        public string BS01 { get; set; }
        public string BS02 { get; set; }
        public string BS03 { get; set; }
        public string BS04 { get; set; }
        public string BS05 { get; set; }
        public string LS01 { get; set; }
        public string LS02 { get; set; }
        public string LS03 { get; set; }
        public string LS04 { get; set; }
        public string LS05 { get; set; }
        public string LS06 { get; set; }
        public string LS07 { get; set; }
        public string LS08 { get; set; }
        public string LS09 { get; set; }
        public string LS10 { get; set; }
    }
}
