//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Labels = new HashSet<Label>();
        }
    
        public string ID { get; set; }
        public string PatientType { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string AgeUnit { get; set; }
        public string PS01 { get; set; }
        public string PS02 { get; set; }
        public string PS03 { get; set; }
        public string PS04 { get; set; }
        public string PS05 { get; set; }
        public string PS06 { get; set; }
        public string PS07 { get; set; }
        public string PS08 { get; set; }
        public string PS09 { get; set; }
        public string PS10 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte[] photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Label> Labels { get; set; }
    }
}
