//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintTemplateTable
    {
        public int Reiteration { get; set; }
        public string HospitalID { get; set; }
        public string LabelTypeID { get; set; }
        public string InOutID { get; set; }
        public int CommandID { get; set; }
        public int ParameterID { get; set; }
        public int Start { get; set; }
        public int Length { get; set; }
        public string CommandInfo { get; set; }
    }
}
