//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityRuleTable
    {
        public int SerialID { get; set; }
        public string TestOrder { get; set; }
        public string TubeColor { get; set; }
        public int SortID { get; set; }
        public int LongestSortTime { get; set; }
        public Nullable<bool> ISUse { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
