//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueSet
    {
        public int id { get; set; }
        public int windowNum { get; set; }
        public string mac { get; set; }
        public string screenDisplay { get; set; }
        public Nullable<int> screenFlag { get; set; }
        public string bannerAdress { get; set; }
        public Nullable<int> isSpecialWindow { get; set; }
        public string tipText { get; set; }
        public string logoImage { get; set; }
        public string hospitalName { get; set; }
        public Nullable<int> refresh { get; set; }
        public Nullable<int> isUsed { get; set; }
    }
}
