//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortRecord
    {
        public int id { get; set; }
        public string barcode { get; set; }
        public string testOrder { get; set; }
        public string testGroup { get; set; }
        public string sortID { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
