//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorting_TubeInfo_M
    {
        public long ID { get; set; }
        public string Barcode { get; set; }
        public string TestItem { get; set; }
        public string TestGroup { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientSex { get; set; }
        public string PatientAge { get; set; }
        public string PatientType { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> ExecytionTime { get; set; }
        public Nullable<int> RepeatInsert { get; set; }
        public Nullable<int> SortingState { get; set; }
        public Nullable<int> SignForState { get; set; }
        public string Reserve1 { get; set; }
        public string Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public string Reserve5 { get; set; }
        public string Reserve6 { get; set; }
        public string Reserve7 { get; set; }
        public string Reserve8 { get; set; }
        public string Reserve9 { get; set; }
        public string Reserve10 { get; set; }
        public string Reserve11 { get; set; }
        public string Reserve12 { get; set; }
        public string Reserve13 { get; set; }
        public string Reserve14 { get; set; }
        public string Reserve15 { get; set; }
    }
}
