//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string ID { get; set; }
        public string ClassID { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public bool IsUse { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
