//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_TIME_TABEL
    {
        public string TEST_ORDER { get; set; }
        public string TEST_CYCLE { get; set; }
        public string TEST_REPORT_LOCATION { get; set; }
        public string RESERVE1 { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public decimal RESERVE4 { get; set; }
        public decimal RESERVE5 { get; set; }
        public decimal RESERVE6 { get; set; }
    }
}
