//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LRs = new HashSet<LR>();
        }
    
        public string ID { get; set; }
        public string LoginName { get; set; }
        public string TrueName { get; set; }
        public string Password { get; set; }
        public string RoleID { get; set; }
        public string DepartmentID { get; set; }
        public string PostID { get; set; }
        public string Tel { get; set; }
        public bool IsUse { get; set; }
        public string Note { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LR> LRs { get; set; }
        public virtual Post Post { get; set; }
    }
}
