//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEHOU.PM.DB.dbLabelInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Sorting_TubeGroup
    {
        public int Id { get; set; }
        public int GroupNo { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string TestGroup { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string TestItem { get; set; }
        public Nullable<int> ToDayNumber { get; set; }
        public string Reserve1 { get; set; }
        public string Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public string Reserve5 { get; set; }
    }
}
